CREATE DATABASE ATMPROJECT;
USE ATMPROJECT;
CREATE TABLE NEWUSER (USERNAME VARCHAR(20),PIN INT,ACCOUNT_NUMBER INT,EMAIL VARCHAR(30),BALANCE INT,DEPOSIT INT,WITHDRAW INT);
ALTER TABLE NEWUSER ADD primary key (PIN);
ALTER TABLE NEWUSER MODIFY ACCOUNT_NUMBER LONG; 
SELECT * FROM NEWUSER ;


